### ISSUE TITLE
Implement Google user authentication

### ISSUE THREAD

**Issue by ronnieima** [ronnieima/quiz-app#10]
# Feature
Upgrade the app by adding users to login through their Google account to store data. I can possibly add a leaderboard with users' pictures and names, too.

## Todo
- [ ] Create a login screen view (May have to implement React Router to route through different pages)
- [ ] Implement authentication tools. User should be able to login with their Google account (JSON Web Tokens (JWT) or PassportJS ?)
- [ ] Setup a database (MongoDB or PostgreSQL)
